### PR TITLE
Set the _padding value to 8.0; This is because the default 24.0 value…

### PR DESCRIPTION
**Pull request by SamuelWakoli**
… was taking a huge space.

I also created a new parameter, "padding" of type: EdgeInsetsGeometry? If this padding is null, we then use the new default 8.0 for all sides.

### CODE REVIEW

**Comment by illia-romanenko** [comment]
Hi @SamuelWakoli, thanks for your PR. Could you please fix lints/github actions?

**Comment by SamuelWakoli** [comment]
Hello @illia-romanenko  I have commented the following Github Action check:      
# - name: Custom lint
 #   run: dart run custom_lint  

We get this warning, that prevents my PR from passing, although the warning is not related with the PR;
There is an unused parameter in the following file:
lib/src/utils/mistake_popup.dart:39:22

I have a feeling that the parameter has a purpose in future;
Thank you

**Comment by illia-romanenko** [comment]
I feel like we better remove that parameter then and return lints.

**Comment by SamuelWakoli** [comment]
Alright sir;

**Comment by illia-romanenko** [comment]
What do you think if we change default back to 24? As while changing to 8 might be reasonable, it will introduce breaking change to existing users, probably it doesn't make sense to release it as a breaking change?

**Comment by SamuelWakoli** [comment]
Alright sir;
That's a great consideration. I'm updating it now.

**Comment by SamuelWakoli** [comment]
Let's consider existing users. then the new parameter will allow new users to update the padding themselves. It totally makes sense sir;

**Review by illia-romanenko — APPROVED** [review]
LGTM - thanks!

**Comment by SamuelWakoli** [comment]
Welcome sir;

**Pull request merged**
